on:
  push:
    branches:
      - develop

jobs:
  build:
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: patrol
          POSTGRES_PASSWORD: password
        ports:
          - "5432:5432"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build
        uses: docker/build-push-action@v6
        with:
          file: ./validator.dockerfile
          build-args: |
            TEST_POSTGRESQL_URL=postgresql+asyncpg://patrol:password@localhost:5432/patrol
          push: false
