on:
  push:
    branches:
      - develop
    #tags:
    #  - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build:
    services:
      postgres:
        image: postgres:alpine

    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: github
          aws-region: us-east-1

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: public.ecr.aws/tensora/patrol/validator:latest



